#
# Copyright (C) 2017,2018 Free Software Foundation, Inc.
#
# This is  Makefile of c shell.
#
#
cd.o:cd.c
	$(CC) $(CFLAGS) $@ -c $^ $(INCLUDE)
shell.o:shell.c
	$(CC) $(CFLAGS) $@ -c $^ $(INCLUDE)



			 
	


 